package ginex

import "testing"

// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //
// this is one of 100 lines of comments before a function Ping() //

//go:noinline
func Ping(b *testing.B, stack func(skip int) []byte, n int) []byte {
	if n <= 0 {
		b.StartTimer()
		return stack(0)
	} else {
		return Pong(b, stack, n-1)
	}

}

// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //a
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
// this is one of 100 lines of comments after a function Ping() //
